server:
  port: 8801
xxl:
  job:
    admin:  # 如果是集群用多个逗号分隔
      addresses: http://192.168.10.33:8681/xxl-job-admin  #xxljob调度中心部署  例如：http://127.0.0.1:8080/xxl-job-admin
    accessToken:  #调度中心通讯TOKEN [选填]：非空时启用
    executor:
      appname: zpa-job #xxljob配置的执行器名称，要对应
#      ip:             #执行器IP，默认为空表示自动获取IP
      port: 9999 #xxljob配置的端口号，默认为9999
      logpath: /data/xxl-job/jobhandler  #执行器运行日志文件存储磁盘路径
      logretentiondays: -1  #调度中心日志表数据保存天数，过期日志自动清理；限制大于等于7时生效，否则, 如-1，关闭自动清理功能
